[phases.setup]
nixPkgs = ["python3", "gcc", "gnumake", "nodejs", "pnpm"]

[phases.install]
cmds = [
  "python3 --version",
  "pnpm install",
  "pnpm exec node-gyp rebuild --directory node_modules/better-sqlite3"
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm start"

