[phases.setup]
nixPkgs = ["python3", "gcc", "gnumake", "nodejs", "pnpm", "sqlite"]

[phases.install]
cmds = [
  "python3 --version",
  "pnpm install"
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm start"

